# SERVIDOR
server.port=${PORT:8080}
spring.application.name=controle-celular

# BANCO DE DADOS
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/controle_celular}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET:minha-chave-secreta-padrao-super-longa-aqui-2024}

# LOG
logging.level.org.hibernate.SQL=DEBUG